#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' zsh | grep "install ok installed")
echo "Checking for zsh: $PKG_OK"
if [ "" = "$PKG_OK" ]; then
    echo "No zsh. Setting up zsh."
    sudo apt-get --yes install zsh
fi

DIR="$HOME/.oh-my-zsh"
if [ ! -d "$DIR" ]; then
    echo "Checking for oh-my-zsh: not installed"
    PKG_CURL_OK=$(dpkg-query -W --showformat='${Status}\n' curl | grep "install ok installed")
    echo "Checking for curl: $PKG_CURL_OK"
    if [ "" = "$PKG_CURL_OK" ]; then
        echo "No curl. Setting up curl."
        sudo apt-get --yes install curl
    fi

    echo "No oh-my-zsh. Setting up oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    echo "Checking for oh-my-zsh: installed"
fi

DIR="$HOME/.oh-my-zsh/custom/plugins/artisan"
if [ ! -d "$DIR" ]; then
    echo "Checking for zsh-artisan plugin: not installed"
    PKG_CURL_OK=$(dpkg-query -W --showformat='${Status}\n' curl | grep "install ok installed")
    echo "Checking for curl: $PKG_CURL_OK"
    if [ "" = "$PKG_CURL_OK" ]; then
        echo "No curl. Setting up curl."
        sudo apt-get --yes install curl
    fi

    echo "No zsh-artisan plugin. Setting up zsh-artisan"
    git clone https://github.com/owrasor/zsh-artisan.git ~/.oh-my-zsh/custom/plugins/artisan
else
    echo "Checking for zsh-artisan plugin: installed"
fi

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc

# rm -rf $HOME/.tmux.conf
# ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# mkdir -p $HOME/.local/bin

# rm -rf $HOME/.local/bin/t
# ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

# rm -rf $HOME/.config/nvim
# ln -s $DOTFILES/nvim $HOME/.config/nvim
